"""initial schema

Revision ID: 1b1c81817eb8
Revises: 
Create Date: 2026-09-28 13:29:56.576892
"""
from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

revision = '1b1c81817eb8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channels'))
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('thread_ids', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('reaction', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("reaction IN ('up', 'down')", name=op.f('ck_feedback_reaction_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedback'))
    )
    op.create_table('threads',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('channel_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_threads_channel_id_channels')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_threads'))
    )
    op.create_index(op.f('ix_threads_channel_id'), 'threads', ['channel_id'], unique=False)
    op.create_table('embeddings',
    sa.Column('thread_id', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], name=op.f('fk_embeddings_thread_id_threads')),
    sa.PrimaryKeyConstraint('thread_id', name=op.f('pk_embeddings'))
    )
    op.create_index('ix_embeddings_embedding_ivfflat', 'embeddings', ['embedding'], unique=False, postgresql_using='ivfflat', postgresql_with={'lists': '100'}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('messages',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('channel_id', sa.Text(), nullable=False),
    sa.Column('thread_id', sa.Text(), nullable=True),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('permalink', sa.Text(), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', text)", persisted=True), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_messages_channel_id_channels')),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], name=op.f('fk_messages_thread_id_threads')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index(op.f('ix_messages_channel_id'), 'messages', ['channel_id'], unique=False)
    op.create_index('ix_messages_search_vector', 'messages', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_messages_thread_id'), 'messages', ['thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_thread_id'), table_name='messages')
    op.drop_index('ix_messages_search_vector', table_name='messages', postgresql_using='gin')
    op.drop_index(op.f('ix_messages_channel_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_embeddings_embedding_ivfflat', table_name='embeddings', postgresql_using='ivfflat', postgresql_with={'lists': '100'}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('embeddings')
    op.drop_index(op.f('ix_threads_channel_id'), table_name='threads')
    op.drop_table('threads')
    op.drop_table('feedback')
    op.drop_table('channels')
    # ### end Alembic commands ###
