"""add ingestion_runs

Revision ID: 2de7d79fd7ad
Revises: 1b1c81817eb8
Create Date: 2026-09-28 14:02:08.155012
"""
from alembic import op
import sqlalchemy as sa


revision = '2de7d79fd7ad'
down_revision = '1b1c81817eb8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('messages_fetched', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('threads_processed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('messages_filtered', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('chunks_created', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('errors_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_ingestion_runs_channel_id_channels')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_runs'))
    )
    op.create_index(op.f('ix_ingestion_runs_channel_id'), 'ingestion_runs', ['channel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingestion_runs_channel_id'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    # ### end Alembic commands ###
